In [6]:
import pandas as pd
import numpy as np
import sklearn

In [7]:
df = pd.read_excel('Sources.xlsx', encoding='latin-1')

In [8]:
df['Adresses'] = df['Adresses'].str.lower()

In [9]:
df_sources = sklearn.utils.shuffle(df) #on secoue l'échantillon afin de réorganiser aléatoirement l'échantillon

In [10]:
df_sources

Adresses  Target
172973                                              30320       0
64251    12 rue du val d'osne, 94415, saint maurice cedex       1
131545                                              63670       0
217835                                            léopold       0
20530         170 rue du college, 59700, marcq en baroeul       1
299628                                              ahmed       0
133577                                              75019       0
15070                  110 avenue de france, 75013, paris       1
51290        265 route de la baronne, 6640, saint jeannet       1
6655    immeuble river ouest 80 quai voltaire, 95870, ...       1
214497                                               enok       0
42322   24 avenue j foucault zi parc europe bp 93017, ...       1
234594                                              irène       0
11300             141 rue garibaldi, 69211, lyon cedex 03       1
25932       1, bis rue abel bergaigne, 62002, arras cedex       1
124604                                              92100       0
246579                                               enyo       0
222021                                              toni        0
267641                                               lisa       0
228823                                             assiya       0
305165                                              katia       0
133382                                              92150       0
188514                                              74330       0
94656                1 rue louis lagorgette, 33150, cenon       1
171747                                              25000       0
193497                                              75007       0
199743                                              75003       0
58486        9 rue de la résistance, 42000, saint-étienne       1
159826                                              77270       0
230730                                             myriam       0
...                                                   ...     ...
18497     3 avenue andre malraux, 92300, levallois perret       1
214967                                            flannan       0
171425                                              97743       0
308543                                madame bovary, 1856       0
68583             les petites blaches, 26700, pierrelatte       1
33643                        35 rue marbeuf, 75008, paris       1
26562                  174, rue de charonne, 75128, paris       1
913                     res. aquilon apt h004, 71100, lux       1
223899                                               abel       0
144020                                              69003       0
139840                                              33820       0
261853                                               éléa       0
240843                                             flavio       0
245955                                              deryn       0
92192            70, rue jacques babinet, 31100, toulouse       1
274871                                           violette       0
23162                    71 rue de grenelle, 75007, paris       1
79593                          8 rue halévy, 75009, paris       1
138482                                              78600       0
269937                                             jayden       0
258875                                             lucien       0
114851                                              13340       0
79770                 8 rue jean moulin, 47210, villereal       1
87241       20 i de la valenceaude, 16160, gond pontouvre       1
249807                                             layton       0
49907                   10 rue rouviere, 13001, marseille       1
49222               16, boulevard carnot, 3100, montlucon       1
250486                                             marcel       0
195876                                              11400       0
167617                 

In [11]:
df_sources.to_excel("shuffle.xlsx")

In [12]:
df_sources['Adresses'].dtypes #le type des données est O soit un mix de caractère, string, et chiffre

dtype('O')

In [13]:
from sklearn.model_selection import train_test_split 
#on divise l'échantillon en train et test 
X = df_sources['Adresses']
y = df_sources['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((207596,), (102250,), (207596,), (102250,))

In [7]:
# X_train

### modèle Naives Bayes en Multinomial

In [14]:
from sklearn.feature_extraction.text import CountVectorizer 
#on vectorize les données a étudier afin d'être comprise par le modèle
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train.astype('U'))
X_test_counts = count_vect.transform(X_test.astype('U'))
X_train_counts.shape, X_test_counts.shape

((207596, 49587), (102250, 49587))

In [15]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train_counts, y_train)

y_pred = clf.predict(X_train_counts)
      
# gnb = GaussianNB()
# y_pred = gnb.fit(X_train, y_train).predict(y_test)
# print("Number of mislabeled points out of a total %d points : %d" 
#        % (X_test.shape[0], (y_train != y_pred).sum()))

In [16]:
from sklearn import metrics #on imprime les métrics d'évaluations
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    136945
           1       0.98      0.99      0.99     70651

    accuracy                           0.99    207596
   macro avg       0.99      0.99      0.99    207596
weighted avg       0.99      0.99      0.99    207596



In [17]:
from sklearn.naive_bayes import MultinomialNB

y_pred = clf.predict(X_test_counts) 

In [18]:
from sklearn import metrics
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     67902
           1       0.98      0.99      0.99     34348

    accuracy                           0.99    102250
   macro avg       0.99      0.99      0.99    102250
weighted avg       0.99      0.99      0.99    102250



In [12]:
metrics.confusion_matrix(y_test, y_pred)

array([[66796,   714],
       [  240, 34500]], dtype=int64)

In [13]:
X_sources= df_sources['Adresses']
y_sources = df_sources['Target']

X_count = count_vect.fit_transform(X_sources.astype('U'))

In [15]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(MultinomialNB(), X_count, y, cv=8)
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.9908084  0.9906793  0.99083422 0.99052439 0.99031783 0.99086003
 0.98995637 0.99062718]


### modèle Naives Bayes en Multinomial + TF - IDF

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer 
# #on vectorize les données a étudier afin d'être comprise par le modèle
# count_vect = CountVectorizer()
# X_train_counts = count_vect.fit_transform(X_train.astype('U'))
# X_test_counts = count_vect.transform(X_test.astype('U'))
# X_train_counts.shape, X_test_counts.shape

In [24]:
from sklearn.feature_extraction.text import TfidfTransformer 
#afin d'afiner le modèle, on instaure un système de poids probabilitste en Tf -IDF

tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_test_tf = tf_transformer.transform(X_test_counts)
X_train_tf.shape, X_test_tf.shape

(207596, 49361)

In [25]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train_tf, y_train)

# y_pred = clf.predict(X_train_tf) 

In [14]:
# from sklearn import metrics
# print(metrics.classification_report(y_train, y_pred))

In [28]:
y_pred = clf.predict(X_test_tf) 
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     67449
           1       0.98      0.99      0.99     34801

    accuracy                           0.99    102250
   macro avg       0.99      0.99      0.99    102250
weighted avg       0.99      0.99      0.99    102250



In [29]:
metrics.confusion_matrix(y_test, y_pred)

array([[66720,   729],
       [  198, 34603]], dtype=int64)

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer

tf_transformer = TfidfTransformer(use_idf=False).fit(X_count)
X_tf = tf_transformer.transform(X_count)
X_tf.shape

(309846, 56569)

In [31]:
from sklearn.model_selection import cross_val_score


scores = cross_val_score(MultinomialNB(), X_tf, y, cv=8)
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.99197026 0.99147969 0.99166043 0.99124732 0.99096331 0.99096331
 0.99163461 0.99119523]


### On change de dataset avec une répartion 99% adresses 1% de bruit

In [49]:
df1 = pd.read_excel('99-1.xlsx', encoding='latin-1')
# df_991

In [50]:
df_991 = sklearn.utils.shuffle(df1)

In [51]:
df_991.to_excel('df_991.xlsx')

In [27]:
df_991.head(5)

Adresses  Target
78876      47/53 rue raspail, 92594, levallois-perret       1
41429  6 trine de l asile, 38260, la cote saint andre       1
68738                    13 rue bertin, 3000, moulins       1
14069   196 traverse de la marjolaine, 13420, gemenos       1
63521         8 rue jules simon, 37000, tours cedex 1       1

In [17]:
# len(df_991)

In [28]:
from sklearn.model_selection import train_test_split 
#on divise l'échantillon en train et test 
X = df_991['Adresses']
y = df_991['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((67000,), (33001,), (67000,), (33001,))

In [29]:
from sklearn.feature_extraction.text import CountVectorizer #on vectorize les données a étudier afin d'être comprise par le modèle
count_vect = CountVectorizer()
X_tr991_counts = count_vect.fit_transform(X_train.astype('U'))
X_te991_counts = count_vect.transform(X_test.astype('U'))
X_tr991_counts.shape, X_te991_counts.shape

((67000, 35606), (33001, 35606))

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer #afin d'afiner le modèle, on instaure un système de poids probabilitste en Tf -IDF

tf_transformer = TfidfTransformer(use_idf=False).fit(X_tr991_counts)
X_tr991_tf = tf_transformer.transform(X_tr991_counts)
X_te991_tf = tf_transformer.transform(X_te991_counts)
X_tr991_tf.shape, X_te991_tf.shape

((67000, 35606), (33001, 35606))

In [31]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha =  0.00001, fit_prior = True) 
# clf = MultinomialNB()
clf.fit(X_tr991_tf, y_train)

y_pred = clf.predict(X_te991_tf)

In [32]:
from sklearn import metrics #on imprime les métrics d'évaluations
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.31      0.47       333
           1       0.99      1.00      1.00     32668

    accuracy                           0.99     33001
   macro avg       0.99      0.65      0.73     33001
weighted avg       0.99      0.99      0.99     33001



In [33]:
metrics.confusion_matrix(y_test, y_pred)

array([[  102,   231],
       [    2, 32666]], dtype=int64)

In [34]:
from sklearn.model_selection import cross_val_score

X = count_vect.fit_transform(df_991['Adresses'].astype('U'))
y = df_991['Target']

scores = cross_val_score(MultinomialNB(), X, y, cv=8)
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.98792097 0.98808095 0.98808    0.98872    0.98712    0.98904
 0.98848    0.98887911]


In [35]:
from sklearn.model_selection import GridSearchCV
import time
#Le gridsearch permet de tester les hyperparamètres en même temps dans plusieurs config afin d'en retiré le meilleur paramétrage

parameters = {'alpha': (1, 0.1, 0.01, 0.001, 0.0001, 0.00001), 'fit_prior' : (True, False)}
gs_clf = GridSearchCV(MultinomialNB(), parameters, cv=5, n_jobs=-1)
gs_clf.fit(X, y)  
#print("done in {0}s".format(time() - t0))  
print("Best score: {0}".format(gs_clf.best_score_))  
print("Best parameters set:")  
best_parameters = gs_clf.best_estimator_.get_params()
for param_name in sorted(list(parameters.keys())):  
            print("\t{0}: {1}".format(param_name, best_parameters[param_name]))

Best score: 0.994560054399456
Best parameters set:
	alpha: 1e-05
	fit_prior: True


### On change de dataset avec une répartion 1% adresses 99% de bruit

In [37]:
df2 = pd.read_excel('1-99.xlsx', encoding='latin-1')


In [40]:
df_199 = sklearn.utils.shuffle(df2)
# df_199

In [52]:
df_199.to_excel('df_199.xlsx')

In [ ]:
df_991.to_excel('df_991.xlsx')

In [41]:
from sklearn.model_selection import train_test_split 
#on divise l'échantillon en train et test 
X = df_199['Adresses']
y = df_199['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=44)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((66999,), (33000,), (66999,), (33000,))

In [42]:
from sklearn.feature_extraction.text import CountVectorizer #on vectorize les données a étudier afin d'être comprise par le modèle
count_vect = CountVectorizer()
X_tr199_counts = count_vect.fit_transform(X_train.astype('U'))
X_te199_counts = count_vect.transform(X_test.astype('U'))
X_tr199_counts.shape, X_te199_counts.shape

((66999, 16412), (33000, 16412))

In [43]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_tr199_counts, y_train)

y_pred = clf.predict(X_te199_counts)

In [44]:
from sklearn import metrics #on imprime les métrics d'évaluations
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     32667
           1       1.00      0.92      0.95       333

    accuracy                           1.00     33000
   macro avg       1.00      0.96      0.98     33000
weighted avg       1.00      1.00      1.00     33000



In [45]:
metrics.confusion_matrix(y_test, y_pred)

array([[32666,     1],
       [   28,   305]], dtype=int64)

In [46]:
from sklearn.model_selection import cross_val_score

X = count_vect.fit_transform(df_199['Adresses'].astype('U'))
y = df_199['Target']

scores = cross_val_score(MultinomialNB(), X, y, cv=8)
print("Cross-validation scores: {}".format(scores))

Cross-validation scores: [0.99976    0.99992    0.99992    0.9996     0.99976    0.99984
 0.99984    0.99967997]


In [47]:
from sklearn.model_selection import GridSearchCV
import time
parameters = {'alpha': (1, 0.1, 0.01, 0.001, 0.0001, 0.00001), 'fit_prior' : (True, False)}
gs_clf = GridSearchCV(MultinomialNB(), parameters, cv=5, n_jobs=-1)
gs_clf.fit(X, y)  
#print("done in {0}s".format(time() - t0))  
print("Best score: {0}".format(gs_clf.best_score_))  
print("Best parameters set:")  
best_parameters = gs_clf.best_estimator_.get_params()
for param_name in sorted(list(parameters.keys())):  
            print("\t{0}: {1}".format(param_name, best_parameters[param_name]))

Best score: 0.99979999799998
Best parameters set:
	alpha: 1
	fit_prior: True
